### ISSUE TITLE
Issue getting the module to work

### ISSUE THREAD

**Issue by Migushthe2nd** [whalehub/custom-certificate-authorities#1]
I'm on Android 11 with Magisk 25201.
After installing the module and following the steps, the android system still gives a notification the cert is in the user store
<img width="369" alt="image" src="https://user-images.githubusercontent.com/22274715/181490450-ad304a56-aab1-4447-99fe-35cbb0a4fb9c.png">
The module is not listed in the system certs list. I'm not sure what's going wrong here

**Comment by whalehub** [comment]
This module doesn't move certs from the user store to the system store, so it's expected that any certificates you manually added to the user store would still be there after installing this module.

As for why it doesn't show up in the system store, can you please paste the output of the command in step 5 here?

**Comment by Migushthe2nd** [comment]
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 3941249117 (0xeaeab05d)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = PortSwigger, ST = PortSwigger, L = PortSwigger, O = PortSwigger, OU = PortSwigger CA, CN = PortSwigger CA
        Validity
            Not Before: Jul 28 10:22:26 2014 GMT
            Not After : Jul 28 10:22:26 2032 GMT
        Subject: C = PortSwigger, ST = PortSwigger, L = PortSwigger, O = PortSwigger, OU = PortSwigger CA, CN = PortSwigger CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:a7:6d:00:26:7d:b8:b0:42:9e:8f:09:f8:83:05:
                    4d:a3:93:b9:88:23:c0:3d:67:2b:65:ec:4a:60:8a:
                    89:c9:8e:c2:43:e5:61:04:e8:46:0e:45:ca:3a:f3:
                    0b:2a:cf:9b:b0:bc:8a:ea:df:e9:c9:3e:07:49:2b:
                    10:02:8e:f3:fd:14:eb:9b:12:f9:cb:33:1b:32:39:
                    cd:88:16:72:97:1a:70:1b:02:2d:97:e3:8c:b6:a3:
                    9e:d1:bd:43:28:28:d4:6b:86:26:30:e3:5e:79:5b:
                    f7:52:8b:59:43:3d:7e:6c:a8:4a:ec:42:47:06:26:
                    e3:67:f9:ec:ab:e5:c3:8e:07:3c:5b:92:77:3d:ca:
                    97:2b:08:b9:57:0c:b0:bf:99:cd:2a:84:85:c0:7c:
                    fa:e9:12:e0:0e:b2:9b:aa:8b:91:54:21:15:e2:60:
                    1c:df:9c:f8:4a:5d:62:04:97:ab:e8:5f:f6:05:ca:
                    4e:d9:20:a0:6b:f8:6b:a4:b5:2b:b7:d1:08:3c:2b:
                    6d:ef:ce:20:01:29:4d:90:32:ad:2b:f5:15:7b:00:
                    ae:5f:72:12:8f:e9:ee:e7:89:b2:12:de:d1:5c:2f:
                    7c:fe:7c:b4:f2:fc:40:61:54:f6:c4:51:db:e3:7a:
                    8e:b5:bc:35:a2:2d:7e:90:3c:cb:37:c1:8d:70:5b:
                    f1:e9
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         6a:b3:66:81:68:8b:15:d8:7f:54:ff:9c:2d:03:7c:d5:33:1d:
         53:cd:d1:31:82:b8:34:cc:29:c9:71:98:0b:b8:c3:a6:85:f1:
         be:30:25:62:d5:9a:45:e5:9d:70:4e:49:e2:49:e8:00:de:c2:
         66:f1:8b:05:9f:75:ea:da:56:69:a7:9a:2d:a2:a9:d9:96:18:
         f1:8d:46:42:56:ac:64:90:7c:99:fc:34:10:2a:f3:cc:7f:8b:
         04:e2:45:17:4f:e8:b1:57:55:7a:3b:14:d7:22:59:f9:ed:4a:
         cd:5e:ba:50:57:f9:2e:b9:24:8c:ea:41:c1:40:ab:5a:1d:84:
         bb:a3:15:a6:1d:e5:ed:5c:de:41:a0:88:18:b5:ad:19:80:33:
         2d:6e:20:ab:d0:5b:d1:a9:cc:2c:b4:9f:93:80:f3:4f:60:9d:
         06:8c:4a:cd:47:a7:ce:cf:75:91:53:4b:4f:63:90:03:f9:3e:
         89:da:2f:b9:31:31:a0:88:59:3e:7b:01:f8:c9:92:d6:e8:64:
         e7:df:9a:a0:b6:8b:14:cd:ac:97:cb:78:1e:e8:ea:55:47:d2:
         b8:f1:49:b7:72:2c:83:f2:b5:0c:75:05:f0:2b:97:b0:7e:b0:
         1e:9c:05:52:ee:a9:aa:21:d4:0b:67:38:61:7a:cb:10:e3:7e:
         47:59:bd:79
```
The `-----BEGIN CERTIFICATE-----` seemed to be missing, because in step 6, openssl would error with `34359836736:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE`

**Comment by Migushthe2nd** [comment]
Oh sorry, seems I wasn't entirely clear. The module doesn't work, even after copying the part to the new certificate.

**Comment by whalehub** [comment]
> Oh sorry, seems I wasn't entirely clear. The module doesn't work, even after copying the part to the new certificate.

No worries. What is the output of steps 5 and 6 after you manually fixed the certificate?

**Comment by Wapitiii** [comment]
The module also doesn't work for me properly, done everything right, it also shows up in system, but it somehow doesn't use it.
<img src="https://user-images.githubusercontent.com/39195287/181933691-cac0d06e-a131-4158-a5ce-514ec860dfd7.png" width="400" height="800">
<img src="https://user-images.githubusercontent.com/39195287/181933696-4f93be85-8fd7-4090-80b0-7c8566ed7101.png" width="400" height="800">

**Comment by whalehub** [comment]
> The module also doesn't work for me properly, done everything right, it also shows up in system, but it somehow doesn't use it.
What are you referring to with "it"? What is not using the certificate?

**Comment by Wapitiii** [comment]
> What are you referring to with "it"? Which application is not using the certificate?

Every application doesn't work, can't see the unencrypted traffic with for example mitmproxy.

**Comment by whalehub** [comment]
> Every application doesn't work, can't see the encrypted traffic with for example mitmproxy.

I'm sorry, but troubleshooting your configuration of mitmproxy is beyond the scope of this issue.

> Also im using Android 12, maybe thats the issue?

It's possible. I've only ever tested this module on Android 11 since that's the version I use on my phone.

**Comment by Migushthe2nd** [comment]
> This module doesn't move certs from the user store to the system store, so it's expected that any certificates you manually added to the user store would still be there after installing this module.

I haven't added these certificates to the user store manually. I moved them to the folder, and they're now shown in the user store list.

**Comment by Wapitiii** [comment]
> I'm sorry, but troubleshooting your configuration of mitmproxy is beyond the scope of this issue.

It's not an issue with mitmproxy, on my other android device that runs android 9 it works perfectly.

**Comment by Wapitiii** [comment]
So i've now tried using https://github.com/Magisk-Modules-Repo/movecert , it works with this without issues.

**Comment by whalehub** [comment]
I'm using Android 12.1 on my phone now and this module is still working fine for me.
